### ISSUE TITLE
Please clarify how to integrate trove with coverall service 

### ISSUE THREAD

**Issue by melezhik** [pheix/raku-trove#2]
Looks like the doc does not explain why. I wish to run trove from my CI and then publish coverage to coverall service …

**Comment by pheix** [comment]
I will update README, but briefly speaking all you need is just to setup the env. Initially `Trove` was simple bash script targeted to GitLab. And there it was relied on 2 env vars:

1. `CI_JOB_ID` - [predefined](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) GitLab CI job identifier
2. `COVERALLSTOKEN` - Coveralls secret repo [token](https://docs.coveralls.io/api-introduction).

For now `Trove` also operates with these vars, so to integrate to Coveralls you can simply:

```bash
CI_JOB_ID=`date +%s` COVERALLSTOKEN=your-secret-roken RAKULIB=./lib trove-cli -c --f=`pwd`/x/trove-configs/test.conf.yaml.explore --p=yq
```

**Comment by pheix** [comment]
If you +/- familiar with GitLab you can check https://gitlab.com/pheix-pool/core-perl6/-/pipelines, I use `Trove` as a primary test tools since the late Nov. As I said GitLab setup `CI_JOB_ID` automatically and `COVERALLSTOKEN` is configured with CI/CD [protected variables](https://docs.gitlab.com/ee/ci/variables/#add-a-cicd-variable-to-a-project):

![Screenshot from 2022-12-31 23-23-42](https://user-images.githubusercontent.com/6272762/210155017-1914d50d-f46b-49ac-8334-f8e749c23faa.png)

So, usage with GitLab is quite transparent/friendly, how it looks at GitHub actions or other CI/CD systems - it's the another point of investigation.

**Comment by melezhik** [comment]
works with SparrowCI pipeline - https://ci.sparrowhub.io/report/2398

Worth to mention in the documentation, that COVERALLSTOKEN should be repo token, not API token, this is not clear from coverall docs ...

**Comment by pheix** [comment]
Details are added to `README.md`: https://github.com/pheix/raku-trove#setup-automatic-coverage-upload, `Trove` [v0.0.34](https://github.com/pheix/raku-trove/commit/fa8dfcd83a2b0d2aebd222776dee804b05a2c202)

**Comment by melezhik** [comment]
Thanks !
